server:
  port: 8080
  servlet:
    context-path: /MyShop

spring:
# 数据库连接
  datasource:
    url: jdbc:mysql://111.230.15.168/myshop
    username: hzzone
    password: 123456
    type: org.apache.commons.dbcp2.BasicDataSource
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapper-locations: classpath:edu/scu/my_shop/mapper/*.xml
  type-aliases-package: edu.scu.my_shop.mapper.model
  