server:
  port: 8080
  servlet:
    context-path: /
pagehelper:
#  dialect: mysql
  reasonable: true
  support-methods-arguments: true

# path to save file(DO NOT ADD "/" AT THE END)
# TODO: configure correct path
image:
  user-image-folder-path: /Users/zhouqinchun/IdeaProjects/my_shop/src/main/resources/static/images/users/
  user-image-relate-path: /images/users
  product-image-folder-path: /Users/zhouqinchun/IdeaProjects/my_shop/src/main/resources/static/images/users/
  product-image-relate-path: /images/products

spring:
  mvc:
    static-path-pattern: /**
#  #解决时间差
#  jackson:
#    time-zone: GMT+8


#      prefix: /
#      suffix: .html
# 数据库连接
  datasource:
    url: jdbc:mysql://111.230.15.168/myshop?characterEncoding=utf8
    username: hzzone
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    tomcat:
      max-wait: 10000
      max-active: 30


mybatis:
  mapperlocations: /mapper/**Mapper.xml
  type-aliases-package: edu.scu.my_shop.entity


