server:
  port: 8080
  servlet:
    context-path: /

spring:
  mvc:
    static-path-pattern: /**

#      prefix: /
#      suffix: .html
# 数据库连接
  datasource:
    url: jdbc:mysql://111.230.15.168/myshop?characterEncoding=utf8
    username: hzzone
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapperlocations: /mapper/**Mapper.xml
  type-aliases-package: edu.scu.my_shop.entity
  